#!/bin/bash
# hooks/build
# https://docs.docker.com/docker-cloud/builds/advanced/

# $IMAGE_NAME var is injected into the build so the tag is correct.
echo "[***] Build hook running"

docker build \
    --build-arg GIT_TOKEN=$GIT_TOKEN \
    -t $IMAGE_NAME .

